meta_product_name: "Peer To Pair"
meta_title: "Peer To Pair - Connect internally, create opportunities."
meta_description: "Meet peers from your company, people you wouldn't have talked to otherwise. Based on people's availabilities and meeting preferences."
meta_image: "peertopair-og-image.png"
